#!/bin/bash
#
declare -r MYSQLDUMP_EXE=/cygdrive/c/MAMP/bin/mysql/bin/mysqldump.exe
declare -r USERNAME=dd_backup
declare -r PASSWORD=dd_backup_9959
declare -r BACKUP_DIR=/cygdrive/c/lfz/c11_doubledate/backups
#
declare NOW=$(date +"%F-%T")
$MYSQLDUMP_EXE -e -u$USERNAME -p$PASSWORD -hlocalhost double_date > $BACKUP_DIR/dd_backup_$NOW.sql
